name: Test

on:
  push:
    paths-ignore:
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.abc.outputs.all }}"
          echo "Added+Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"

          IFS=' ' read -ra paths <<< "${{ steps.abc.outputs.added_modified }}"

          for path in "${paths[@]}"; do
            if [[ "$path" == *swagger.json* ]]; then
              echo "Swagger.json found in path: $path"
              # add the code to temp.
              # clone the code and make sure it is inside /home/runner/projects
            else
              echo "Swagger.json not found in path: $path"
            fi
          done
