name: Automation tests running on Nexial Docker
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
    - uses: docker/setup-docker@v3
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -t roompot/mdminfraci .
        docker run -it --name nexial roompot/mdminfraci
             
        
