name: Automation tests running on Nexial Docker
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build docker images
        run: docker build -t roompot/mdminfraci .
        
      - name: Run tests
        run: docker run --mount type=bind,source=/tmp/nexial-output,target=/home/projects/tests --name nexial roompot/mdminfraci
             
        
