name: roompot-workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - DEV
          - QA
          - PROD
      versionNumber:
        description: 'Version Number'
        required: true
        type: integer

jobs:
  run-curl-commands:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Environment Variables
      run: |
        echo "export environment=${{ github.event.inputs.environment }}" >> $HOME/.bashrc
        echo "export version_number=${{ github.event.inputs.version_number }}" >> $HOME/.bashrc

    - name: Run Script based on Version
      run: |
        source $HOME/.bashrc
        version_folder="data${version_number}"
        if [[ ! $version_number =~ ^[0-9]+$ ]]; then
          echo "Invalid version number specified."
          exit 1
        fi
        if [ -d "$version_folder" ]; then
          bash "$version_folder/v${version_number}.sh"
        else
          echo "Folder for version number $version_number not found."
          exit 1
        fi